Update
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

diff --git a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
--- a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
+++ b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
@@ -143,14 +143,14 @@ data:
 
             if [[ "$#" -lt 2 ]]; then  
                 echo "ERROR: path missing - example : 'elfbot symlink /storage/realdebrid-zurg/movies'"
-                exit 1
-            elif [[ ! -d "$2" ]]; then
-                echo "ERROR: $2 does not exist"
-                exit 1   
+                exit 1 
             elif [[ "$2" == "report" ]]; then
                 echo "Generating symlink report, see /symlinks/report.txt for details"
                 echo report > /elfbot/symlink
-                exit 0          
+                exit 0      
+            elif [[ ! -d "$2" ]]; then
+                echo "ERROR: $2 does not exist"
+                exit 1                      
             else
                 ITEMPATH=$2
             fi            
