Avoid self-symlinking
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

diff --git a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
--- a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
+++ b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
@@ -164,6 +164,12 @@ data:
                 ITEMPATH=$2
             fi
 
+            # Never symlink ourselves!
+            if [[ $ITEMPATH == *"/storage/symlinks"* ]]; then
+                echo "ERROR: Can't symlink a source in /storage/symlinks (#deathbysymlink)"
+                exit 1
+            fi
+
             # Get ready to create symlinks
             mkdir -p /storage/symlinks/.symlink_cache
 
