Improve alldebrid
Signed-off-by: David Young <davidy@funkypenguin.co.nz>

diff --git a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
--- a/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
+++ b/charts/other/myprecious/templates/configmaps/configmap-filebrowser-elfbot.yaml
@@ -19,28 +19,41 @@ data:
         echo "elfbot backup <app>               : creates a dated backup folder in under /config/<app>"
         echo "elfbot claim plex <token>         : claims a plex server"
         echo "elfbot env <app> <key>=<value>    : set an env var inside an app (advanced beta feature)"
-        echo "elfbot symlinkify                 : import remotely-mounted, read-only media as symlinks"
+        echo "elfbot symlink <storage-mount>    : import remotely-mounted, read-only media as symlinks"
         echo
-    fi
-
-    if [[ ! -d "/storage/config/$2" && $2 -ne "all" ]]; then
-        echo "WARNING: /config/$2 does not exist"
-        exit 1
     fi
 
     case $1 in
 
         "restart")
+
+            if [[ ! -d "/storage/config/$2" && $2 -ne "all" ]]; then
+                echo "WARNING: /config/$2 does not exist"
+                exit 1
+            fi
+                    
             echo "restarting $2..."
             echo restart > /elfbot/$2
             ;;
 
         "pause")
+
+            if [[ ! -d "/storage/config/$2" && $2 -ne "all" ]]; then
+                echo "WARNING: /config/$2 does not exist"
+                exit 1
+            fi
+
             echo "pausing $2 for 5 min..."
             echo pause > /elfbot/$2
             ;;     
 
         "env")
+
+            if [[ ! -d "/storage/config/$2" ]]; then
+                echo "WARNING: /config/$2 does not exist"
+                exit 1
+            fi
+
             if [[ "$#" -lt 3 ]]; then  
                 echo syntax is "elfbot env KEY=VALUE"
                 exit 1
@@ -50,6 +63,12 @@ data:
             ;;                        
 
         "reset")
+
+            if [[ ! -d "/storage/config/$2" && $2 -ne "all" ]]; then
+                echo "WARNING: /config/$2 does not exist"
+                exit 1
+            fi
+
             if [[ "$3" != "--yesiamsure" ]]; then
                 echo potentially dangerous! add \'--yesiamsure\' after your reset command to force
                 exit 1
@@ -59,6 +78,12 @@ data:
             ;;
 
         "backup")   
+
+            if [[ ! -d "/storage/config/$2" && $2 -ne "all" ]]; then
+                echo "WARNING: /config/$2 does not exist"
+                exit 1
+            fi
+
             if [[ "$2" == "all" ]]; then
                 APPS=$(ls /storage/config)
                 echo "Backing up multiple apps, restarting each with a 1 min delay, this may take a while..."
@@ -109,11 +134,14 @@ data:
             fi
             ;;      
 
-        "symlinkify")
+        "symlink")
 
             if [[ "$#" -lt 2 ]]; then  
-                echo path missing - specify one like "/storage/realdebrid-zurg/movies"
+                echo "ERROR: path missing - example : 'elfbot symlink /storage/realdebrid-zurg/movies'"
                 exit 1
+            elif [[ ! -d "$2" ]]; then
+                echo "ERROR: $2 does not exist"
+                exit 1   
             else
                 ITEMPATH=$2
             fi            
